version: 2
updates:
  # Python dependencies (MkDocs, etc.) - using UV
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Capp3"
    assignees:
      - "Capp3"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "uv"

  # Node.js dependencies (prompt-server)
  - package-ecosystem: "npm"
    directory: "/prompt-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Capp3"
    assignees:
      - "Capp3"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "nodejs"
      - "prompt-server"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Capp3"
    assignees:
      - "Capp3"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"

  # Docker dependencies (if using Docker)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "Capp3"
    assignees:
      - "Capp3"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
