name: researchbug-support
version: 0.0.1
networks:
  support_network:
    driver: bridge
volumes:
  n8n-redis:
  n8n-postgres:
services:
  n8n-redis:
    container_name: n8n-redis
    image: redis:bookworm
    networks:
      - support_network
    restart: unless-stopped
    ports:
      - ${SUPPORT_REDIS_PORT:-6379}:6379
    volumes:
      - n8n-redis:/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 3s
  n8n-pgvector:
    container_name: n8n-pgvector
    image: pgvector/pgvector:pg17-bookworm
    volumes:
      - n8n-postgres:/var/lib/postgresql/data
    depends_on:
      n8n-postgres:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: ${SUPPORT_POSTGRES_PASSWORD:-support-password}
      POSTGRES_USER: ${SUPPORT_POSTGRES_USER:-support-user}
      POSTGRES_DB: ${SUPPORT_POSTGRES_DB:-support}
    networks:
      - support_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 768M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      timeout: 5s
  n8n-postgres:
    image: postgres:17-bookworm
    restart: unless-stopped
    container_name: n8n-postgres
    shm_size: 128mb
    volumes:
      - n8n-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SUPPORT_POSTGRES_PASSWORD:-support-password}
      POSTGRES_USER: ${SUPPORT_POSTGRES_USER:-support-user}
      POSTGRES_DB: ${SUPPORT_POSTGRES_DB:-support}
    networks:
      - support_network
    ports:
      - ${SUPPORT_POSTGRES_PORT:-5432}:5432
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      timeout: 5s
  adminer:
    image: adminer
    restart: unless-stopped
    container_name: n8n-adminer
    depends_on:
      n8n-postgres:
        condition: service_healthy
    networks:
      - support_network
    ports:
      - ${SUPPORT_ADMINER_PORT:-8080}:8080
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      timeout: 5s
