site_name: Research Bug 0.0.5
site_description: Multi-agent AI workflow for document enhancement and collaboration using n8n, LangChain, and Telegram integration
site_author: cappy
site_url: https://capp3.github.io/n8n-research-bug/
repo_url: https://github.com/Capp3/n8n-research-bug
repo_name: Capp3/n8n-research-bug
edit_uri: edit/main/docs/

# Copyright notice
copyright: Copyright &copy; 2025 cappy

# Configuration
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  hljs_style: base16-gruvbox-light-soft
  hljs_style_dark: base16-gruvbox-dark-hard

# Plugins
plugins:
  - search:
      lang: en
#  - mermaid2:
#      arguments:
#        theme: base
#        themeVariables:
#          primaryColor: '#059669'
#          primaryTextColor: '#1f2937'
#          primaryBorderColor: '#059669'
#          lineColor: '#6b7280'
#          secondaryColor: '#f3f4f6'
#          tertiaryColor: '#ffffff'

# Markdown extensions
markdown_extensions:
  - codehilite:
      use_pygments: true
      css_class: highlight
  - fenced_code
  - tables
  - toc:
      permalink: true
      permalink_title: "Link to this section"
#  - pymdownx.superfences
#  - pymdownx.highlight:
#      anchor_linenums: true
#      line_spans: __span
#      pygments_lang_class: true
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.tabbed:
#      alternate_style: true
#  - pymdownx.details
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.smartsymbols
#  - pymdownx.tilde
#  - pymdownx.caret
  - attr_list
  - md_in_html

# Page tree
nav:
  - Home: index.md
  - Project Brief: projectbrief.md
  - Technical Summary: technical.md
  - System Prompts: system-prompts.md
  - Quick Start: QUICK_START.md
  - Implementation:
      - Overview: implementation/index.md
      - Setup Guide: implementation/setup-guide.md
      - Configuration: implementation/configuration.md
      - Testing: implementation/testing.md
      - Chat Memory: implementation/chat-memory.md
      - Chat Memory API: implementation/chat-memory-api.md
      - Credentials Guide: implementation/credentials-guide.md
      - Environment Setup: implementation/environment-setup.md
      - Troubleshooting: implementation/troubleshooting.md
      - Workflow Analysis: implementation/workflow-analysis.md
  - Prompts:
      - Overview: prompts/index.md
      - Schema Reference: prompts/schema.md
  - Contributing:
      - Overview: contributing/index.md
      - Prompt Contributions: contributing/prompt-contributions.md
      - Code Contributions: contributing/code-contributions.md
  - Status:
      - Overview: status/index.md
      - Project Status: status/project-status.md
      - Tasks: status/tasks.md
      - Progress: status/progress.md
      - Active Context: status/activeContext.md
      - N8N Workflow Analysis: status/n8n-workflow-analysis.md
      - Build Summary: status/build-summary-credentials.md
      - Chat Memory Implementation: status/postgresql-chat-memory-implementation-summary.md
      - Documentation Updates: status/documentation-updates-summary.md
      - Implementation Completion: status/implementation-completion-20250128.md
      - Implementation MCP Services: status/implementation-mcp-services-20250128.md
      - MkDocs Mermaid Update: status/mkdocs-mermaid-update-summary.md
      - MkDocs YAML Fix: status/mkdocs-yaml-fix-summary.md
      - Reflection MCP Implementation: status/reflection-mcp-implementation-20250128.md
      - UV Usage Verification: status/uv-usage-verification-summary.md
      - GitHub Workflows Review: status/github-workflows-review-summary.md
  - Test Data:
      - Overview: test-data/index.md
      - Sample Document: test-data/sample-document.md
      - Style Instructions: test-data/style-instructions.md
      - Submission Brief: test-data/submission-brief.md
      - Test Log Template: test-data/test-log-template.md
  - Archive:
      - Overview: archive/index.md
      - Document Refactoring: archive/document-refactoring-20250128.md
      - MCP Server Refactoring: archive/mcp-server-refactoring-20250128.md
      - MCP Services Implementation: archive/mcp-services-implementation-20250128.md
      - Prompt System Simplification: archive/prompt-system-simplification-20250128.md
      - N8N Patterns Refactoring: archive/n8n-patterns-refactoring-20250128.md
      - Documentation Refactor: archive/documentation-refactor-20250904.md
      - Foundation Setup: archive/foundation-setup-prompt-system-20250903.md
      - GitHub Actions Workflows: archive/github-actions-workflows-20250903.md
      - GitHub Pages Deployment: archive/github-pages-deployment-20250903.md
      - Makefile Enhancement: archive/makefile-enhancement-20250903.md
      - N8N Credentials Documentation: archive/n8n-credentials-documentation-20250904.md
      - N8N Workflow Analysis: archive/n8n-workflow-analysis-20250903.md
      - Support Services Documentation: archive/support-services-documentation-20250903.md
      - Variable Mapping Workflow: archive/variable-mapping-workflow-alignment-20250903.md
      - Comprehensive Archives:
          - MCP Integration: archive/comprehensive-archives/mcp-integration-consolidated.md
          - N8N Refactoring: archive/comprehensive-archives/n8n-refactoring-consolidated.md
          - Prompt System: archive/comprehensive-archives/prompt-system-consolidated.md
      - Creative:
          - MCP Implementation Plan: archive/creative/mcp-implementation-plan.md
          - UI/UX Design: archive/creative/uiux.md
      - Individual Files:
          - Documentation Organization: archive/individual-files/DOCUMENTATION_ORGANIZATION_SUMMARY.md
          - N8N MCP Integration: archive/individual-files/N8N_MCP_INTEGRATION_SUMMARY.md
          - Algorithm: archive/individual-files/algorithm.md
          - Architecture: archive/individual-files/architecture.md
          - Decisions: archive/individual-files/decisions.md
          - Document Refactoring Architecture: archive/individual-files/document-refactoring-architecture-design.md
          - Document Refactoring UI/UX: archive/individual-files/document-refactoring-uiux-design.md
          - MCP Integration Options: archive/individual-files/mcp-integration-options.md
          - MCP Servers: archive/individual-files/mcp-servers.md
          - N8N MCP Integration: archive/individual-files/n8n-mcp-integration.md
          - N8N Patterns Refactoring Plan: archive/individual-files/n8n-patterns-refactoring-plan.md
          - N8N Patterns Refactoring: archive/individual-files/n8n-patterns-refactoring.md
          - Prompt System Simplification Plan: archive/individual-files/prompt-system-simplification-plan.md
          - Prompt System Simplification: archive/individual-files/prompt-system-simplification.md
      - Reflection 2025-01-28:
          - Document Refactoring: archive/reflection/2025-01-28/reflection-document-refactoring-20250128.md
          - MCP Refactoring: archive/reflection/2025-01-28/reflection-mcp-refactoring-20250128.md
          - N8N Patterns Refactoring: archive/reflection/2025-01-28/reflection-n8n-patterns-refactoring-20250128.md
          - Prompt Simplification: archive/reflection/2025-01-28/reflection-prompt-simplification-20250128.md
      - Additional Archives:
          - Archive Completion Summary: archive/archive-completion-summary.md
          - Archive Continuation Summary: archive/archive-continuation-summary.md
          - Archive Preparation Analysis: archive/archive-preparation-analysis.md
          - Archive Strategy Completion: archive/archive-strategy-completion-summary.md
          - Background Services Plan: archive/background-services-refactoring-plan.md
          - Contributing Documentation: archive/contributing-documentation-20250903.md
          - Creative Phase Design: archive/creative-phase-prompt-system-design-20250903.md
          - Document Organization: archive/document-organization-structure-20250903.md
          - Document Reorganization: archive/document-reorganization-summary.md
          - Documentation Refactor Summary: archive/documentation-refactor-summary.md
          - Implementation Plan PostgreSQL: archive/implementation-plan-postgresql-chat-memory.md
          - Mermaid Test: archive/mermaid-test.md
          - Refactor Summary: archive/refactor-summary.md
          - Reflection Documentation: archive/reflection-documentation-refactor.md

# Exclude archive files from navigation but allow them to be built
extra_css:
  - css/extra.css

# Allow warnings without failing the build
strict: false
