site_name: Research Bug 0.0.2
site_description: Multi-agent AI workflow for document enhancement and collaboration using n8n, LangChain, and Telegram integration
site_author: cappy
site_url: https://capp3.github.io/n8n-research-bug/
repo_url: https://github.com/Capp3/n8n-research-bug
repo_name: Capp3/n8n-research-bug
edit_uri: edit/main/docs/

# Copyright notice
copyright: Copyright &copy; 2025 cappy

# Configuration
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
  hljs_style: base16-gruvbox-light-soft
  hljs_style_dark: base16-gruvbox-dark-hard

# Plugins
plugins:
  - search:
      lang: en
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          primaryColor: '#059669'
          primaryTextColor: '#1f2937'
          primaryBorderColor: '#059669'
          lineColor: '#6b7280'
          secondaryColor: '#f3f4f6'
          tertiaryColor: '#ffffff'

# Markdown extensions
markdown_extensions:
  - codehilite:
      use_pygments: true
      css_class: highlight
  - fenced_code
  - tables
  - toc:
      permalink: true
      permalink_title: "Link to this section"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.caret
  - attr_list
  - md_in_html

# Page tree
nav:
  - Home: index.md
  - Project Brief: projectbrief.md
  - Technical Summary: technical.md
  - System Prompts: system-prompts.md
  - Quick Start: QUICK_START.md
  - Implementation:
      - Overview: implementation/index.md
      - Setup Guide: implementation/setup-guide.md
      - Configuration: implementation/configuration.md
      - Makefile Commands: implementation/makefile-commands.md
      - Testing: implementation/testing.md
      - Variable Mapping: implementation/variable-mapping.md
      - GitHub Pages: implementation/github-pages-deployment.md
      - Prompt Server: implementation/prompt-server.md
      - Chat Memory: implementation/chat-memory.md
      - Chat Memory API: implementation/chat-memory-api.md
      - MCP Servers: implementation/mcp-servers.md
  - Prompts:
      - Overview: prompts/index.md
      - Schema Reference: prompts/schema.md
  - Contributing:
      - Overview: contributing/index.md
      - Prompt Contributions: contributing/prompt-contributions.md
  - Archive: archive/index.md
  - Reflection: reflection/index.md
  - Creative: creative/index.md
  - Status:
      - Overview: status/index.md
      - Project Status: status/project-status.md
      - Tasks: status/tasks.md
      - Build Summary: status/build-summary-credentials.md
      - Chat Memory Implementation: status/postgresql-chat-memory-implementation-summary.md
      - Documentation Updates: status/documentation-updates-summary.md
      - Cinder Theme Implementation: status/cinder-theme-implementation-summary.md
  - Test Data:
      - Overview: test-data/index.md
  - Mermaid Test: mermaid-test.md
