site_name: Research Bug 0.0.5
site_description: Multi-agent AI workflow for document enhancement and collaboration using n8n and Telegram integration
site_author: cappy
site_url: https://capp3.github.io/n8n-research-bug/
repo_url: https://github.com/Capp3/n8n-research-bug
repo_name: Capp3/n8n-research-bug
edit_uri: edit/main/docs/

# Copyright notice
copyright: Copyright &copy; 2025 cappy

# Configuration
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

# Allow warnings without failing the build
strict: false
