[project]
name = "n8n-research-bug"
version = "0.0.5"
description = "Development Support for n8n Research bug"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-mermaid2-plugin>=1.2.2",
]
