name: Scheduled Test

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:

  test-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          version: 'latest'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Test documentation
        run: |
          uv venv
          uv pip install -r scripts/requirements.txt
          source .venv/bin/activate
          mkdocs build --clean --strict
          echo "✅ Documentation build successful"

      - name: Test Mermaid functionality
        run: |
          source .venv/bin/activate
          # Test that Mermaid charts are properly rendered
          mkdocs build --clean
          # Check if Mermaid test page exists and builds
          test -f site/mermaid-test/index.html
          echo "✅ Mermaid functionality test passed"
