name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd prompt-server
          npm install

      - name: Run tests
        run: |
          cd prompt-server
          npm test

      - name: Test API endpoints
        run: |
          cd prompt-server
          npm start &
          sleep 5

          # Test health endpoint
          curl -f http://localhost:3000/api/health

          # Test prompts endpoint
          curl -f http://localhost:3000/api/prompts

          echo "✅ API endpoints are working"

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          version: 'latest'

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          uv pip install -r scripts/requirements.txt

      - name: Build documentation
        run: |
          source .venv/bin/activate
          mkdocs build --clean --strict

      - name: Test documentation
        run: |
          echo "✅ Documentation build successful"
