name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'prompt-server/package-lock.json'

      - name: Install dependencies
        run: |
          cd prompt-server
          npm ci

      - name: Run tests
        run: |
          cd prompt-server
          npm test

      - name: Test API endpoints
        run: |
          cd prompt-server
          npm start &
          sleep 5

          # Test health endpoint
          curl -f http://localhost:3000/api/health

          # Test prompts endpoint
          curl -f http://localhost:3000/api/prompts

          echo "✅ API endpoints are working"

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Build documentation
        run: |
          mkdocs build --clean --strict

      - name: Test documentation
        run: |
          echo "✅ Documentation build successful"
